# Generated by Django 3.2.16 on 2022-10-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='заголовок')),
                ('short_description', models.TextField(verbose_name='короткое описание')),
                ('long_description', models.TextField(verbose_name='длинное описание')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('latitude', models.FloatField(verbose_name='широта')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
    ]
