# Generated by Django 4.0.8 on 2022-10-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number'], 'verbose_name': 'фотография', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title'], 'verbose_name': 'локация', 'verbose_name_plural': 'локации'},
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(db_index=True, verbose_name='позиция'),
        ),
    ]
